### ISSUE TITLE
在华为应用市场上线审核不通过

### ISSUE THREAD

**Issue by earlyCloud** [PandaQQ/react-native-xinge-push#2]
我没有配置华为通道，我不知道是不是因为这个，我不知道怎么配置华为通道。。。下面这些是审核反馈。

审核结果：不通过。

审核意见：错误:28: 集成HMS需要将证书文件打包到APK中，请直接将assets目录拷贝到应用工程根目录。 ;一般:10: 资源文件集成错误，请检查文件（/res/values/strings.xml,/res/values-zh-rCN/strings.xml,/res/layout/hms_download_progress.xml） ;提示:17: 应用接入API：()

**Comment by PandaQQ** [comment]
Android证书没配置？那不用说华为不会通过，没有一个平台会给你审核通过的
