### ISSUE TITLE
是否准备升级到信鸽 SDK 最新版？

### ISSUE THREAD

**Issue by someok** [PandaQQ/react-native-xinge-push#3]
信鸽 SDK 已升级了，请问是否有兴趣也升级到最新版？

- Android SDK V4.3.5
- iOS SDK V3.3.7

**Comment by PandaQQ** [comment]
已经升级到最新了～

**Comment by PandaQQ** [comment]
iOS SDK 3.3.7 
Android SDK 4.3.2 （信鸽官方建议是4.3.0 以上，Android SDK更新打算在 React Native 升级至 0.6x 的时候一起升级）

**Comment by PandaQQ** [comment]
@someok Android 也更新到最新SDK了

**Comment by finalreturn** [comment]
> @someok Android 也更新到最新SDK了

大佬，在app杀死的情况下，调起通知栏的消息，在rn中能监听到信息做处理吗。我还没尝试用起来

**Comment by PandaQQ** [comment]
@finalreturn 能……

**Comment by finalreturn** [comment]
> @finalreturn 能……

sorry，我刚起跑了下example，在home键下划掉app，通过推送。消息时达到了，但是点击通知栏后，启动app后，后续没有任何事件触发，也就是app只能在前台活跃时，触发点击消息才能触发notification；

还一个就是：notification的监听，在点击后消息后无法触发clicked=true；

我期望在app杀死的情况，厂商渠道推送的消息，在点击通知栏调起app时，能在js内处理得到的数据；
现状时，我只能通过点击通知栏的信息调起app，后续不能做任何处理；

**Comment by PandaQQ** [comment]
我下班了⋯不過你可以開個新的issue⋯我明天回覆下⋯

finalreturn <notifications@github.com>于2019年11月22日 周五下午5:42写道：
