### ISSUE TITLE
app杀死情况下，调起通知栏启动app，获取传递的信息

### ISSUE THREAD

**Issue by finalreturn** [PandaQQ/react-native-xinge-push#4]
**描述**
1.notification的监听，在点击后消息后无法触发clicked=true；
2.期望在app杀死的情况，推送消息后，在点击通知栏的消息后启动app后，能得到事件触发，或时其他的方式得到传递的值，并处理得到的数据；

现状，我只能推送消息到达后，通过点击通知栏的信息启动app，后续不能做任何处理，也就是推送消息只能单纯的推送消息，也不能对消息进行处理；

**复现步骤**
重现步骤:
1. 下载example；
2. 启动工程，真机测试；

**预期的行为**
期望在app杀死的情况，推送消息后，在点击通知栏的消息后启动app后，能得到事件触发，或时其他的方式得到传递的值，并处理得到的数据；

**截图**
-

**手机 (请填写下面信息):**
 - 手机型号： [e.g. 小米 NODE 7]
 - 系统版本： [e.g. Android 9.0]
 - 版本 [e.g. 0.8]

**附加信息**
版本为example依赖的版本，我看到的version是0.8.0
期待有更新版本，依赖最新的rn，能有好解决方式，感谢。

**Comment by PandaQQ** [comment]
@finalreturn 
1.notification的监听，在点击后消息后无法触发clicked=true；小米通道走的推送，法触发clicked=true 这个属性是无用的。平台差异性有关。
2. 期望在app杀死的情况，推送消息后，在点击通知栏的消息后启动app后，能得到事件触发，或时其他的方式得到传递的值，并处理得到的数据；需要使用下述方法主动去获取通知信息。
```
  /**
   * 获取初始通知（点击通知后）
   * @private
   */
  _getInitialNotification() {
    XGPush.getInitialNotification().then((result) => {
      alert(JSON.stringify(result));
    });
  }
```
3.  关于版本问题 直接 yarn 或者 npm install --save https://github.com/PandaQQ/react-native-xinge-push.git 即可。

**Comment by finalreturn** [comment]
> @finalreturn
> 1.notification的监听，在点击后消息后无法触发clicked=true；小米通道走的推送，法触发clicked=true 这个属性是无用的。平台差异性有关。
> 2. 期望在app杀死的情况，推送消息后，在点击通知栏的消息后启动app后，能得到事件触发，或时其他的方式得到传递的值，并处理得到的数据；需要使用下述方法主动去获取通知信息。
> 
> ```
>   /**
>    * 获取初始通知（点击通知后）
>    * @private
>    */
>   _getInitialNotification() {
>     XGPush.getInitialNotification().then((result) => {
>       alert(JSON.stringify(result));
>     });
>   }
> ```
> 
> 1. 关于版本问题 直接 yarn 或者 npm install --save https://github.com/PandaQQ/react-native-xinge-push.git 即可。

感谢回复。

我在尝试启动example后，从信鸽官方推送，附加参数，点击通知栏，启动app，点击_getInitialNotification，尝试得到信息，但是没有得到期望的效果，无论如何尝试得到的数据始终为null。

再一个想问下，能在的react-native的0.60版本使用吗，尝试链接依赖后找不到包一系列的包
 Could not resolve com.tencent.....

**Comment by PandaQQ** [comment]
@finalreturn  
1. 你走的是什么通道？ 小米通道信鸽官方推送是不行的。因为杀死App之后，还想收到通知，除非是华为，小米或者FCM （海外）的手机。国产机很多都会直接杀死信鸽的服务。
请参考：
```
Android intent 测试
https://xg.qq.com/docs/android_access/android_faq.html#消息点击事件以及跳转页面方法

测试过上述连接给出的方法再做总结,下面这段代码不行，获取不到参数，但是和使用无关：
	 
	 Uri uri = getIntent().getData();
 	 if (uri != null) {                
		String url = uri.toString();
		UrlQuerySanitizer sanitizer = new UrlQuerySanitizer();
		sanitizer.setUnregisteredParameterValueSanitizer(UrlQuerySanitizer.getAllButNulLegal());
 		sanitizer.parseUrl(url);
 		String value1 = sanitizer.getValue("key1");
 		String value2 = sanitizer.getValue("key2");
 		Log.i("XG" , "value1 = " + value1 + " value2 = " + value2);
 	}
intent 调用sample,注意key要符合定义，否则库收不到参数。(title, content和custom_content)
xgscheme://com.xg.push/notify_detail?title=aa&content=bb&custom_content=<json string>
```
2.   我使用0.59 的RN版本的， 0.6X 以上现在还不想升级.......

**Comment by PandaQQ** [comment]
@finalreturn  
1. 你走的是什么通道？ 小米通道信鸽官方推送是不行的。因为杀死App之后，还想收到通知，除非是华为，小米或者FCM （海外）的手机。国产机很多都会直接杀死信鸽的服务。
请参考：
```
Android intent 测试
https://xg.qq.com/docs/android_access/android_faq.html#消息点击事件以及跳转页面方法

测试过上述连接给出的方法再做总结,下面这段代码不行，获取不到参数，但是和使用无关：
	 
	 Uri uri = getIntent().getData();
 	 if (uri != null) {                
		String url = uri.toString();
		UrlQuerySanitizer sanitizer = new UrlQuerySanitizer();
		sanitizer.setUnregisteredParameterValueSanitizer(UrlQuerySanitizer.getAllButNulLegal());
 		sanitizer.parseUrl(url);
 		String value1 = sanitizer.getValue("key1");
 		String value2 = sanitizer.getValue("key2");
 		Log.i("XG" , "value1 = " + value1 + " value2 = " + value2);
 	}
intent 调用sample,注意key要符合定义，否则库收不到参数。(title, content和custom_content)
xgscheme://com.xg.push/notify_detail?title=aa&content=bb&custom_content=<json string>
```
2.   我使用0.59 的RN版本的， 0.6X 以上现在还不想升级.......
